/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marciano;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaMarciano extends javax.swing.JFrame {
    int Marciano, tiro=0;
    /**
     * Creates new form TelaMarciano
     */
    public TelaMarciano() {
        initComponents();
        Random r = new Random();
        Marciano = r.nextInt(100)+1;
    }

   public void tiro(int arvore){
   if (arvore==Marciano){
       JOptionPane.showMessageDialog(null,"Fui atingido");
       System.exit(0);
   }
   if(arvore<Marciano){
       JOptionPane.showMessageDialog(null,"Estou à direita");
       tiro++;
   }
   if(arvore>Marciano){
       JOptionPane.showMessageDialog(null,"Estou à esquerda");
       tiro++;
    }
   if(tiro==5){
      
       JOptionPane.showMessageDialog(null,"Vou levá-lo à marte");
       System.exit(0);
    }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B82 = new javax.swing.JButton();
        B87 = new javax.swing.JButton();
        B88 = new javax.swing.JButton();
        B81 = new javax.swing.JButton();
        B83 = new javax.swing.JButton();
        B89 = new javax.swing.JButton();
        B86 = new javax.swing.JButton();
        B90 = new javax.swing.JButton();
        B84 = new javax.swing.JButton();
        B85 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        B13 = new javax.swing.JButton();
        B14 = new javax.swing.JButton();
        B15 = new javax.swing.JButton();
        B16 = new javax.swing.JButton();
        B17 = new javax.swing.JButton();
        B18 = new javax.swing.JButton();
        B19 = new javax.swing.JButton();
        B20 = new javax.swing.JButton();
        B21 = new javax.swing.JButton();
        B22 = new javax.swing.JButton();
        B23 = new javax.swing.JButton();
        B24 = new javax.swing.JButton();
        B25 = new javax.swing.JButton();
        B26 = new javax.swing.JButton();
        B27 = new javax.swing.JButton();
        B28 = new javax.swing.JButton();
        B29 = new javax.swing.JButton();
        B30 = new javax.swing.JButton();
        B31 = new javax.swing.JButton();
        B32 = new javax.swing.JButton();
        B33 = new javax.swing.JButton();
        B34 = new javax.swing.JButton();
        B35 = new javax.swing.JButton();
        B36 = new javax.swing.JButton();
        B37 = new javax.swing.JButton();
        B38 = new javax.swing.JButton();
        B39 = new javax.swing.JButton();
        B40 = new javax.swing.JButton();
        B41 = new javax.swing.JButton();
        B42 = new javax.swing.JButton();
        B43 = new javax.swing.JButton();
        B44 = new javax.swing.JButton();
        B45 = new javax.swing.JButton();
        B46 = new javax.swing.JButton();
        B47 = new javax.swing.JButton();
        B48 = new javax.swing.JButton();
        B49 = new javax.swing.JButton();
        B50 = new javax.swing.JButton();
        B51 = new javax.swing.JButton();
        B52 = new javax.swing.JButton();
        B53 = new javax.swing.JButton();
        B54 = new javax.swing.JButton();
        B55 = new javax.swing.JButton();
        B56 = new javax.swing.JButton();
        B57 = new javax.swing.JButton();
        B58 = new javax.swing.JButton();
        B59 = new javax.swing.JButton();
        B60 = new javax.swing.JButton();
        B61 = new javax.swing.JButton();
        B62 = new javax.swing.JButton();
        B63 = new javax.swing.JButton();
        B64 = new javax.swing.JButton();
        B65 = new javax.swing.JButton();
        B66 = new javax.swing.JButton();
        B67 = new javax.swing.JButton();
        B68 = new javax.swing.JButton();
        B69 = new javax.swing.JButton();
        B70 = new javax.swing.JButton();
        B71 = new javax.swing.JButton();
        B72 = new javax.swing.JButton();
        B73 = new javax.swing.JButton();
        B74 = new javax.swing.JButton();
        B75 = new javax.swing.JButton();
        B76 = new javax.swing.JButton();
        B77 = new javax.swing.JButton();
        B78 = new javax.swing.JButton();
        B79 = new javax.swing.JButton();
        B80 = new javax.swing.JButton();
        B91 = new javax.swing.JButton();
        B92 = new javax.swing.JButton();
        B93 = new javax.swing.JButton();
        B94 = new javax.swing.JButton();
        B95 = new javax.swing.JButton();
        B96 = new javax.swing.JButton();
        B97 = new javax.swing.JButton();
        B98 = new javax.swing.JButton();
        B99 = new javax.swing.JButton();
        B100 = new javax.swing.JButton();

        B82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B82ActionPerformed(evt);
            }
        });

        B87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B87ActionPerformed(evt);
            }
        });

        B88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B88ActionPerformed(evt);
            }
        });

        B81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B81ActionPerformed(evt);
            }
        });

        B83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B83ActionPerformed(evt);
            }
        });

        B89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B89ActionPerformed(evt);
            }
        });

        B86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B86ActionPerformed(evt);
            }
        });

        B90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B90ActionPerformed(evt);
            }
        });

        B84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B84ActionPerformed(evt);
            }
        });

        B85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B85ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        B10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });

        B11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });

        B12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });

        B13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B13ActionPerformed(evt);
            }
        });

        B14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B14ActionPerformed(evt);
            }
        });

        B15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B15ActionPerformed(evt);
            }
        });

        B16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B16ActionPerformed(evt);
            }
        });

        B17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B17ActionPerformed(evt);
            }
        });

        B18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B18ActionPerformed(evt);
            }
        });

        B19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B19ActionPerformed(evt);
            }
        });

        B20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B20ActionPerformed(evt);
            }
        });

        B21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B21ActionPerformed(evt);
            }
        });

        B22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B22ActionPerformed(evt);
            }
        });

        B23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B23ActionPerformed(evt);
            }
        });

        B24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B24ActionPerformed(evt);
            }
        });

        B25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B25ActionPerformed(evt);
            }
        });

        B26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B26ActionPerformed(evt);
            }
        });

        B27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B27ActionPerformed(evt);
            }
        });

        B28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B28ActionPerformed(evt);
            }
        });

        B29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B29ActionPerformed(evt);
            }
        });

        B30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B30ActionPerformed(evt);
            }
        });

        B31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B31ActionPerformed(evt);
            }
        });

        B32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B32ActionPerformed(evt);
            }
        });

        B33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B33ActionPerformed(evt);
            }
        });

        B34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B34ActionPerformed(evt);
            }
        });

        B35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B35ActionPerformed(evt);
            }
        });

        B36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B36ActionPerformed(evt);
            }
        });

        B37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B37ActionPerformed(evt);
            }
        });

        B38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B38ActionPerformed(evt);
            }
        });

        B39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B39ActionPerformed(evt);
            }
        });

        B40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B40ActionPerformed(evt);
            }
        });

        B41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B41ActionPerformed(evt);
            }
        });

        B42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B42ActionPerformed(evt);
            }
        });

        B43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B43ActionPerformed(evt);
            }
        });

        B44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B44ActionPerformed(evt);
            }
        });

        B45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B45ActionPerformed(evt);
            }
        });

        B46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B46ActionPerformed(evt);
            }
        });

        B47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B47ActionPerformed(evt);
            }
        });

        B48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B48ActionPerformed(evt);
            }
        });

        B49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B49ActionPerformed(evt);
            }
        });

        B50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B50ActionPerformed(evt);
            }
        });

        B51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B51ActionPerformed(evt);
            }
        });

        B52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B52ActionPerformed(evt);
            }
        });

        B53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B53ActionPerformed(evt);
            }
        });

        B54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B54ActionPerformed(evt);
            }
        });

        B55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B55ActionPerformed(evt);
            }
        });

        B56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B56ActionPerformed(evt);
            }
        });

        B57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B57ActionPerformed(evt);
            }
        });

        B58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B58ActionPerformed(evt);
            }
        });

        B59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B59ActionPerformed(evt);
            }
        });

        B60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B60ActionPerformed(evt);
            }
        });

        B61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B61ActionPerformed(evt);
            }
        });

        B62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B62ActionPerformed(evt);
            }
        });

        B63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B63ActionPerformed(evt);
            }
        });

        B64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B64ActionPerformed(evt);
            }
        });

        B65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B65ActionPerformed(evt);
            }
        });

        B66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B66ActionPerformed(evt);
            }
        });

        B67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B67ActionPerformed(evt);
            }
        });

        B68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B68ActionPerformed(evt);
            }
        });

        B69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B69ActionPerformed(evt);
            }
        });

        B70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B70ActionPerformed(evt);
            }
        });

        B71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B71ActionPerformed(evt);
            }
        });

        B72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B72ActionPerformed(evt);
            }
        });

        B73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B73ActionPerformed(evt);
            }
        });

        B74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B74ActionPerformed(evt);
            }
        });

        B75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B75ActionPerformed(evt);
            }
        });

        B76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B76ActionPerformed(evt);
            }
        });

        B77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B77ActionPerformed(evt);
            }
        });

        B78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B78ActionPerformed(evt);
            }
        });

        B79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B79ActionPerformed(evt);
            }
        });

        B80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B80ActionPerformed(evt);
            }
        });

        B91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B91ActionPerformed(evt);
            }
        });

        B92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B92ActionPerformed(evt);
            }
        });

        B93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B93ActionPerformed(evt);
            }
        });

        B94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B94ActionPerformed(evt);
            }
        });

        B95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B95ActionPerformed(evt);
            }
        });

        B96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B96ActionPerformed(evt);
            }
        });

        B97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B97.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B97ActionPerformed(evt);
            }
        });

        B98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B98ActionPerformed(evt);
            }
        });

        B99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B99ActionPerformed(evt);
            }
        });

        B100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marciano/arvore.gif"))); // NOI18N
        B100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B100ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B29, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B31, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B32, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B33, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B34, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B35, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B36, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B37, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B38, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B39, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B40, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(B41, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B42, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B43, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B44, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B45, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B46, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B47, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B48, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B49, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B50, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(B51, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B52, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B53, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B54, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B55, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B56, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B57, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B58, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B59, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B60, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B61, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B62, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B63, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B64, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B65, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B66, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B67, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B68, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B69, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B70, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(B71, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B72, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B73, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B74, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B75, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B76, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B77, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B78, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B79, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B80, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B91, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B92, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B93, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B94, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B95, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B96, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B97, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B98, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B99, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B100, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B10)
                    .addComponent(B9)
                    .addComponent(B8)
                    .addComponent(B7)
                    .addComponent(B6)
                    .addComponent(B5)
                    .addComponent(B4)
                    .addComponent(B3)
                    .addComponent(B2)
                    .addComponent(B1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B11)
                    .addComponent(B12)
                    .addComponent(B13)
                    .addComponent(B14)
                    .addComponent(B15)
                    .addComponent(B16)
                    .addComponent(B17)
                    .addComponent(B18)
                    .addComponent(B19)
                    .addComponent(B20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B21)
                    .addComponent(B22)
                    .addComponent(B23)
                    .addComponent(B24)
                    .addComponent(B25)
                    .addComponent(B26)
                    .addComponent(B27)
                    .addComponent(B28)
                    .addComponent(B29)
                    .addComponent(B30))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B31)
                    .addComponent(B32)
                    .addComponent(B33)
                    .addComponent(B34)
                    .addComponent(B35)
                    .addComponent(B36)
                    .addComponent(B37)
                    .addComponent(B38)
                    .addComponent(B39)
                    .addComponent(B40))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B41)
                    .addComponent(B42)
                    .addComponent(B43)
                    .addComponent(B44)
                    .addComponent(B45)
                    .addComponent(B46)
                    .addComponent(B47)
                    .addComponent(B48)
                    .addComponent(B49)
                    .addComponent(B50))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B51)
                    .addComponent(B52)
                    .addComponent(B53)
                    .addComponent(B54)
                    .addComponent(B55)
                    .addComponent(B56)
                    .addComponent(B57)
                    .addComponent(B58)
                    .addComponent(B59)
                    .addComponent(B60))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B61)
                    .addComponent(B62)
                    .addComponent(B63)
                    .addComponent(B64)
                    .addComponent(B65)
                    .addComponent(B66)
                    .addComponent(B67)
                    .addComponent(B68)
                    .addComponent(B69)
                    .addComponent(B70))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B71)
                    .addComponent(B72)
                    .addComponent(B73)
                    .addComponent(B74)
                    .addComponent(B75)
                    .addComponent(B76)
                    .addComponent(B77)
                    .addComponent(B78)
                    .addComponent(B79)
                    .addComponent(B80))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B91)
                    .addComponent(B92)
                    .addComponent(B93)
                    .addComponent(B94)
                    .addComponent(B95)
                    .addComponent(B96)
                    .addComponent(B97)
                    .addComponent(B98)
                    .addComponent(B99)
                    .addComponent(B100))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        tiro(1);
        
        
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        tiro(2);
        
        
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        tiro(3);
        
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
       tiro(4);
        
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        tiro(5);
        
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        tiro(6);
        
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
        tiro(7);
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
        tiro(8);
        
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
        tiro(9);
    }//GEN-LAST:event_B9ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
        // TODO add your handling code here:
        tiro(10);
    }//GEN-LAST:event_B10ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
        // TODO add your handling code here:
        tiro(11);
    }//GEN-LAST:event_B11ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed
        // TODO add your handling code here:
        tiro(12);
    }//GEN-LAST:event_B12ActionPerformed

    private void B13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B13ActionPerformed
        // TODO add your handling code here:
        tiro(13);
    }//GEN-LAST:event_B13ActionPerformed

    private void B14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B14ActionPerformed
        // TODO add your handling code here:
        tiro(14);
    }//GEN-LAST:event_B14ActionPerformed

    private void B15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B15ActionPerformed
        // TODO add your handling code here:
        tiro(15);
    }//GEN-LAST:event_B15ActionPerformed

    private void B16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B16ActionPerformed
        // TODO add your handling code here:
        tiro(16);
    }//GEN-LAST:event_B16ActionPerformed

    private void B17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B17ActionPerformed
        // TODO add your handling code here:
        tiro(17);
    }//GEN-LAST:event_B17ActionPerformed

    private void B18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B18ActionPerformed
        // TODO add your handling code here:
        tiro(18);
    }//GEN-LAST:event_B18ActionPerformed

    private void B19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B19ActionPerformed
        // TODO add your handling code here:
        tiro(19);
    }//GEN-LAST:event_B19ActionPerformed

    private void B20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B20ActionPerformed
        // TODO add your handling code here:
        tiro(20);
    }//GEN-LAST:event_B20ActionPerformed

    private void B21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B21ActionPerformed
        // TODO add your handling code here:
        tiro(21);
    }//GEN-LAST:event_B21ActionPerformed

    private void B22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B22ActionPerformed
        // TODO add your handling code here:
        tiro(22);
    }//GEN-LAST:event_B22ActionPerformed

    private void B23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B23ActionPerformed
        // TODO add your handling code here:
        tiro(23);
    }//GEN-LAST:event_B23ActionPerformed

    private void B24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B24ActionPerformed
        // TODO add your handling code here:
        tiro(24);
    }//GEN-LAST:event_B24ActionPerformed

    private void B25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B25ActionPerformed
        // TODO add your handling code here:
        tiro(25);
    }//GEN-LAST:event_B25ActionPerformed

    private void B26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B26ActionPerformed
        // TODO add your handling code here:
        tiro(26);
    }//GEN-LAST:event_B26ActionPerformed

    private void B27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B27ActionPerformed
        // TODO add your handling code here:
        tiro(27);
    }//GEN-LAST:event_B27ActionPerformed

    private void B28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B28ActionPerformed
        // TODO add your handling code here:
        tiro(28);
    }//GEN-LAST:event_B28ActionPerformed

    private void B29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B29ActionPerformed
        // TODO add your handling code here:
        tiro(29);
    }//GEN-LAST:event_B29ActionPerformed

    private void B30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B30ActionPerformed
        // TODO add your handling code here:
        tiro(30);
    }//GEN-LAST:event_B30ActionPerformed

    private void B31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B31ActionPerformed
        // TODO add your handling code here:
                tiro(31);

    }//GEN-LAST:event_B31ActionPerformed

    private void B32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B32ActionPerformed
        // TODO add your handling code here:
                tiro(32);

    }//GEN-LAST:event_B32ActionPerformed

    private void B33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B33ActionPerformed
        // TODO add your handling code here:
                tiro(33);
    }//GEN-LAST:event_B33ActionPerformed

    private void B34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B34ActionPerformed
        // TODO add your handling code here:
        tiro(34);
    }//GEN-LAST:event_B34ActionPerformed

    private void B35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B35ActionPerformed
        // TODO add your handling code here:
        tiro(35);
    }//GEN-LAST:event_B35ActionPerformed

    private void B36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B36ActionPerformed
        // TODO add your handling code here:
        tiro(36);
    }//GEN-LAST:event_B36ActionPerformed

    private void B37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B37ActionPerformed
        // TODO add your handling code here:
        tiro(37);
    }//GEN-LAST:event_B37ActionPerformed

    private void B38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B38ActionPerformed
        // TODO add your handling code here:
        tiro(38);
    }//GEN-LAST:event_B38ActionPerformed

    private void B39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B39ActionPerformed
        // TODO add your handling code here:
        tiro(39);
    }//GEN-LAST:event_B39ActionPerformed

    private void B40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B40ActionPerformed
        // TODO add your handling code here:
        tiro(40);
    }//GEN-LAST:event_B40ActionPerformed

    private void B41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B41ActionPerformed
        // TODO add your handling code here:
        tiro(41);
    }//GEN-LAST:event_B41ActionPerformed

    private void B42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B42ActionPerformed
        // TODO add your handling code here:
        tiro(42);
    }//GEN-LAST:event_B42ActionPerformed

    private void B43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B43ActionPerformed
        // TODO add your handling code here:
        tiro(43);
    }//GEN-LAST:event_B43ActionPerformed

    private void B44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B44ActionPerformed
        // TODO add your handling code here:
        tiro(44);
    }//GEN-LAST:event_B44ActionPerformed

    private void B45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B45ActionPerformed
        // TODO add your handling code here
        tiro(45);
    }//GEN-LAST:event_B45ActionPerformed

    private void B46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B46ActionPerformed
        // TODO add your handling code here:
        tiro(46);
    }//GEN-LAST:event_B46ActionPerformed

    private void B47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B47ActionPerformed
        // TODO add your handling code here:
        tiro(47);
    }//GEN-LAST:event_B47ActionPerformed

    private void B48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B48ActionPerformed
        // TODO add your handling code here:
        tiro(48);
    }//GEN-LAST:event_B48ActionPerformed

    private void B49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B49ActionPerformed
        // TODO add your handling code here:
        tiro(49);
    }//GEN-LAST:event_B49ActionPerformed

    private void B50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B50ActionPerformed
        // TODO add your handling code here:
        tiro(50);
    }//GEN-LAST:event_B50ActionPerformed

    private void B51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B51ActionPerformed
        // TODO add your handling code here:
        tiro(51);
    }//GEN-LAST:event_B51ActionPerformed

    private void B52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B52ActionPerformed
        // TODO add your handling code here:
        tiro(52);
    }//GEN-LAST:event_B52ActionPerformed

    private void B53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B53ActionPerformed
        // TODO add your handling code here:
        tiro(53);
    }//GEN-LAST:event_B53ActionPerformed

    private void B54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B54ActionPerformed
        // TODO add your handling code here:
        tiro(54);
    }//GEN-LAST:event_B54ActionPerformed

    private void B55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B55ActionPerformed
        // TODO add your handling code here:
        tiro(55);
    }//GEN-LAST:event_B55ActionPerformed

    private void B56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B56ActionPerformed
        // TODO add your handling code here:
        tiro(56);
    }//GEN-LAST:event_B56ActionPerformed

    private void B57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B57ActionPerformed
        // TODO add your handling code here:
        tiro(57);        
    }//GEN-LAST:event_B57ActionPerformed

    private void B58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B58ActionPerformed
        // TODO add your handling code here:
        tiro(58);
    }//GEN-LAST:event_B58ActionPerformed

    private void B59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B59ActionPerformed
        // TODO add your handling code here:
        tiro(59);
    }//GEN-LAST:event_B59ActionPerformed

    private void B60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B60ActionPerformed
        // TODO add your handling code here:
        tiro(60);
    }//GEN-LAST:event_B60ActionPerformed

    private void B61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B61ActionPerformed
        // TODO add your handling code here:
        tiro(61);
    }//GEN-LAST:event_B61ActionPerformed

    private void B62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B62ActionPerformed
        // TODO add your handling code here:
        tiro(62);
    }//GEN-LAST:event_B62ActionPerformed

    private void B63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B63ActionPerformed
        // TODO add your handling code here:
        tiro(63);
    }//GEN-LAST:event_B63ActionPerformed

    private void B64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B64ActionPerformed
        // TODO add your handling code here:
        tiro(64);
    }//GEN-LAST:event_B64ActionPerformed

    private void B65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B65ActionPerformed
        // TODO add your handling code here:
        tiro(65);
    }//GEN-LAST:event_B65ActionPerformed

    private void B66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B66ActionPerformed
        // TODO add your handling code here:
        tiro(66);
    }//GEN-LAST:event_B66ActionPerformed

    private void B67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B67ActionPerformed
        // TODO add your handling code here:
        tiro(67);
    }//GEN-LAST:event_B67ActionPerformed

    private void B68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B68ActionPerformed
        // TODO add your handling code here:
        tiro(68);
    }//GEN-LAST:event_B68ActionPerformed

    private void B69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B69ActionPerformed
        // TODO add your handling code here:
        tiro(69);
    }//GEN-LAST:event_B69ActionPerformed

    private void B70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B70ActionPerformed
        // TODO add your handling code here:
        tiro(70);
    }//GEN-LAST:event_B70ActionPerformed

    private void B71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B71ActionPerformed
        // TODO add your handling code here:
        tiro(71);
    }//GEN-LAST:event_B71ActionPerformed

    private void B72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B72ActionPerformed
        // TODO add your handling code here:
        tiro(72);
    }//GEN-LAST:event_B72ActionPerformed

    private void B73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B73ActionPerformed
        // TODO add your handling code here:
        tiro(73);
    }//GEN-LAST:event_B73ActionPerformed

    private void B74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B74ActionPerformed
        // TODO add your handling code here:
        tiro(74);
    }//GEN-LAST:event_B74ActionPerformed

    private void B75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B75ActionPerformed
        // TODO add your handling code here:
        tiro(75);
    }//GEN-LAST:event_B75ActionPerformed

    private void B76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B76ActionPerformed
        // TODO add your handling code here:
        tiro(76);
    }//GEN-LAST:event_B76ActionPerformed

    private void B77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B77ActionPerformed
        // TODO add your handling code here:
        tiro(77);
    }//GEN-LAST:event_B77ActionPerformed

    private void B78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B78ActionPerformed
        // TODO add your handling code here:
        tiro(78);
    }//GEN-LAST:event_B78ActionPerformed

    private void B79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B79ActionPerformed
        // TODO add your handling code here:
        tiro(79);        
    }//GEN-LAST:event_B79ActionPerformed

    private void B80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B80ActionPerformed
        // TODO add your handling code here:
        tiro(80);        
    }//GEN-LAST:event_B80ActionPerformed

    private void B81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B81ActionPerformed
        // TODO add your handling code here:
        tiro(81); 
    }//GEN-LAST:event_B81ActionPerformed

    private void B82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B82ActionPerformed
        // TODO add your handling code here:
        tiro(82); 
    }//GEN-LAST:event_B82ActionPerformed

    private void B83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B83ActionPerformed
        // TODO add your handling code here:
        tiro(83); 
    }//GEN-LAST:event_B83ActionPerformed

    private void B84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B84ActionPerformed
        // TODO add your handling code here:
        tiro(84); 
    }//GEN-LAST:event_B84ActionPerformed

    private void B85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B85ActionPerformed
        // TODO add your handling code here:
        tiro(85); 
    }//GEN-LAST:event_B85ActionPerformed

    private void B86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B86ActionPerformed
        // TODO add your handling code here:
        tiro(86); 
    }//GEN-LAST:event_B86ActionPerformed

    private void B87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B87ActionPerformed
        // TODO add your handling code here:
        tiro(87); 
    }//GEN-LAST:event_B87ActionPerformed

    private void B88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B88ActionPerformed
        // TODO add your handling code here:
        tiro(88); 
    }//GEN-LAST:event_B88ActionPerformed

    private void B89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B89ActionPerformed
        // TODO add your handling code here:
        tiro(89); 
    }//GEN-LAST:event_B89ActionPerformed

    private void B90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B90ActionPerformed
        // TODO add your handling code here:
        tiro(90); 
    }//GEN-LAST:event_B90ActionPerformed

    private void B91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B91ActionPerformed
        // TODO add your handling code here:
        tiro(91); 
    }//GEN-LAST:event_B91ActionPerformed

    private void B92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B92ActionPerformed
        // TODO add your handling code here:
        tiro(92); 
    }//GEN-LAST:event_B92ActionPerformed

    private void B93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B93ActionPerformed
        // TODO add your handling code here:
        tiro(93); 
    }//GEN-LAST:event_B93ActionPerformed

    private void B94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B94ActionPerformed
        // TODO add your handling code here:
        tiro(94); 
    }//GEN-LAST:event_B94ActionPerformed

    private void B95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B95ActionPerformed
        // TODO add your handling code here:
        tiro(95); 
    }//GEN-LAST:event_B95ActionPerformed

    private void B96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B96ActionPerformed
        // TODO add your handling code here:
        tiro(96); 
    }//GEN-LAST:event_B96ActionPerformed

    private void B97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B97ActionPerformed
        // TODO add your handling code here:
        tiro(97); 
    }//GEN-LAST:event_B97ActionPerformed

    private void B98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B98ActionPerformed
        // TODO add your handling code here:
        tiro(98); 
    }//GEN-LAST:event_B98ActionPerformed

    private void B99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B99ActionPerformed
        // TODO add your handling code here:
        tiro(99); 
    }//GEN-LAST:event_B99ActionPerformed

    private void B100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B100ActionPerformed
        // TODO add your handling code here:
        tiro(100); 
    }//GEN-LAST:event_B100ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMarciano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMarciano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMarciano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMarciano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMarciano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B100;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B13;
    private javax.swing.JButton B14;
    private javax.swing.JButton B15;
    private javax.swing.JButton B16;
    private javax.swing.JButton B17;
    private javax.swing.JButton B18;
    private javax.swing.JButton B19;
    private javax.swing.JButton B2;
    private javax.swing.JButton B20;
    private javax.swing.JButton B21;
    private javax.swing.JButton B22;
    private javax.swing.JButton B23;
    private javax.swing.JButton B24;
    private javax.swing.JButton B25;
    private javax.swing.JButton B26;
    private javax.swing.JButton B27;
    private javax.swing.JButton B28;
    private javax.swing.JButton B29;
    private javax.swing.JButton B3;
    private javax.swing.JButton B30;
    private javax.swing.JButton B31;
    private javax.swing.JButton B32;
    private javax.swing.JButton B33;
    private javax.swing.JButton B34;
    private javax.swing.JButton B35;
    private javax.swing.JButton B36;
    private javax.swing.JButton B37;
    private javax.swing.JButton B38;
    private javax.swing.JButton B39;
    private javax.swing.JButton B4;
    private javax.swing.JButton B40;
    private javax.swing.JButton B41;
    private javax.swing.JButton B42;
    private javax.swing.JButton B43;
    private javax.swing.JButton B44;
    private javax.swing.JButton B45;
    private javax.swing.JButton B46;
    private javax.swing.JButton B47;
    private javax.swing.JButton B48;
    private javax.swing.JButton B49;
    private javax.swing.JButton B5;
    private javax.swing.JButton B50;
    private javax.swing.JButton B51;
    private javax.swing.JButton B52;
    private javax.swing.JButton B53;
    private javax.swing.JButton B54;
    private javax.swing.JButton B55;
    private javax.swing.JButton B56;
    private javax.swing.JButton B57;
    private javax.swing.JButton B58;
    private javax.swing.JButton B59;
    private javax.swing.JButton B6;
    private javax.swing.JButton B60;
    private javax.swing.JButton B61;
    private javax.swing.JButton B62;
    private javax.swing.JButton B63;
    private javax.swing.JButton B64;
    private javax.swing.JButton B65;
    private javax.swing.JButton B66;
    private javax.swing.JButton B67;
    private javax.swing.JButton B68;
    private javax.swing.JButton B69;
    private javax.swing.JButton B7;
    private javax.swing.JButton B70;
    private javax.swing.JButton B71;
    private javax.swing.JButton B72;
    private javax.swing.JButton B73;
    private javax.swing.JButton B74;
    private javax.swing.JButton B75;
    private javax.swing.JButton B76;
    private javax.swing.JButton B77;
    private javax.swing.JButton B78;
    private javax.swing.JButton B79;
    private javax.swing.JButton B8;
    private javax.swing.JButton B80;
    private javax.swing.JButton B81;
    private javax.swing.JButton B82;
    private javax.swing.JButton B83;
    private javax.swing.JButton B84;
    private javax.swing.JButton B85;
    private javax.swing.JButton B86;
    private javax.swing.JButton B87;
    private javax.swing.JButton B88;
    private javax.swing.JButton B89;
    private javax.swing.JButton B9;
    private javax.swing.JButton B90;
    private javax.swing.JButton B91;
    private javax.swing.JButton B92;
    private javax.swing.JButton B93;
    private javax.swing.JButton B94;
    private javax.swing.JButton B95;
    private javax.swing.JButton B96;
    private javax.swing.JButton B97;
    private javax.swing.JButton B98;
    private javax.swing.JButton B99;
    // End of variables declaration//GEN-END:variables
}
